from . import assembly
from . import voter
from . import proposal
from . import ballot
from . import partner_merge
from . import res_partner
from . import ir_attachment
from . import mail_compose_message
from . import mail_template
