from . import test_appointment_cron
from . import test_appointment_sms
from . import test_extension_points
from . import test_onetime_link
from . import test_guests
from . import test_meeting_description
from . import test_consent_gating
from . import test_video_room
from . import test_courriels_et_limiteurs
