from . import test_calendar_badges
from . import test_meeting_exchange
from . import test_agenda_changes_since_sent
from . import test_report_autosend
from . import test_report_company_brand
from . import test_public_company_logo
from . import test_discussed_tasks
from . import test_dashboard_access
from . import test_limiteur_borne
from . import test_langue_de_repli
from . import test_avis_assignation
from . import test_mise_en_page_commune
from . import test_planifier_depuis_odj
from . import test_raffinage_automatique
