{
    "name": "BF Work Category - Timesheets",
    "version": "18.0.1.0.2",
    "category": "Hidden",
    "summary": "Work category on timesheet lines, from their task or their project",
    "author": "Les services de consultation Blue Fox, Inc.",
    "website": "https://symbifox.com",
    "license": "LGPL-3",
    "depends": ["bf_work_category", "hr_timesheet"],
    "data": ["views/work_category_views.xml"],
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "auto_install": True,
    "installable": True,
}
