from . import common
from . import test_distribution_counts
from . import test_dashboard
from . import test_document_crons
from . import test_distribution_switch
from . import test_module_boundaries
from . import test_knowledge_matrix
from . import test_release_wizard
from . import test_report_escaping
from . import test_mise_en_page
from . import test_impression_version
from . import test_migration_gel
from . import test_couleur_libre
