"""bf.email.absence — le répondeur d'absence.

Odoo n'en a pas. Ni le cœur, ni l'OCA : `mail_autogenerated_header` fait
l'inverse (il marque NOTRE courrier sortant pour que les répondeurs des autres
se taisent), et `hr_holidays` sait qui est absent sans jamais l'écrire à
personne. Ce module-ci reçoit déjà le courrier et porte déjà les gardes du
réacheminement, alors c'est ici que ça vit.

**La RFC 3834 est le cahier des charges, pas une inspiration.** Un répondeur
qui répond une fois de trop crée une boucle avec le répondeur d'en face, et
deux serveurs se renvoient la balle jusqu'à ce qu'un humain débranche. Les
règles tenues ici, dans l'ordre où elles sont évaluées :

- jamais à un message portant `Auto-Submitted` autre que `no` (§2) ;
- jamais à une liste : en-tête `List-*`, ou `Precedence` valant
  `list` / `junk` / `bulk` (§3.1.8) ;
- jamais à un retour nul, ni à `MAILER-DAEMON`, `owner-*`, `*-request` — les
  adresses que les systèmes automatiques utilisent pour parler (§2) ;
- jamais si l'adresse du destinataire n'est pas explicitement dans `À` ou
  `Cc` : un message reçu en copie cachée ou par une liste ne me vise pas (§3.2) ;
- **une seule réponse par expéditeur** sur une fenêtre glissante, sept jours
  par défaut (§4.3). Comptée par personne, pas par période d'absence : deux
  absences bout à bout ne valent pas deux réponses au même correspondant ;
- la réponse porte `Auto-Submitted: auto-replied`, `In-Reply-To`,
  `References`, un objet préfixé `Auto:`, et **aucune pièce jointe** (§3).

Un écart assumé : la RFC recommande `text/plain`. On envoie du HTML bref,
parce que le corps est rédigé dans Odoo et qu'un lien de prise de rendez-vous
cliquable est la moitié de l'intérêt. Le reste du §3 est tenu.

Ce que la concurrence ne fait pas, et qui tient ici en réutilisant l'existant :
le message **dépend de qui écrit** (les conditions du moteur de règles, donc
« client » et « ce contact précis », pas seulement interne/externe), la relève
**route vraiment** la fiche vers la boîte du collègue, et la période peut
**s'allumer et s'éteindre depuis l'agenda** — parce que le vrai défaut d'un
répondeur n'est pas de mal répondre, c'est qu'on oublie de l'éteindre.
"""

import logging
import re
from datetime import timedelta

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError
from odoo.tools import formataddr, html_escape

_logger = logging.getLogger(__name__)

# RFC 3834 §4.3 recommends seven days as the default.
DEFAULT_COOLDOWN_DAYS = 7
# A per-absence ceiling, for the day something goes wrong upstream.
DEFAULT_DAILY_CAP = 200

# Local-parts that belong to machinery, never to a person expecting an answer.
_ROBOT_LOCALPART = re.compile(
    r"^(mailer-daemon|postmaster|owner-|.*-request$|noreply|no-reply"
    r"|do-not-reply|donotreply|bounce|bounces|notification|notifications)",
    re.IGNORECASE,
)

# Default pattern for calendar-driven absences. Deliberately narrow: a false
# positive here turns the responder on while somebody is at their desk.
DEFAULT_CALENDAR_PATTERN = (
    r"(?i)\b(vacances?|cong[ée]s?|absence|absent[e]?|out\s*of\s*office|ooo"
    r"|f[ée]ri[ée]|sabbatique)\b"
)


class BfEmailAbsence(models.Model):
    _name = "bf.email.absence"
    _description = "Réponse d'absence"
    _order = "is_template desc, date_from desc, id desc"

    name = fields.Char(
        string="Motif",
        required=True,
        help="Pour vous, pas pour l'expéditeur : « Vacances d'été », "
             "« Congrès ». Le message envoyé est celui des lignes ci-dessous.",
    )
    user_id = fields.Many2one(
        comodel_name="res.users",
        string="Personne absente",
        required=True,
        index=True,
        default=lambda self: self.env.user,
        ondelete="cascade",
    )
    company_id = fields.Many2one(
        comodel_name="res.company",
        string="Société",
        default=lambda self: self.env.company,
    )
    active = fields.Boolean(string="Actif", default=True)

    is_template = fields.Boolean(
        string="Message type",
        help="Un message type n'envoie rien : il sert de patron. Une absence "
             "détectée à l'agenda copie ses lignes, ce qui évite d'avoir à "
             "rédiger un message chaque fois qu'on pose une journée.",
    )

    date_from = fields.Datetime(string="Du")
    date_to = fields.Datetime(string="Au")
    state = fields.Selection(
        selection=[
            ("template", "Message type"),
            ("planned", "À venir"),
            ("running", "En cours"),
            ("over", "Terminée"),
            ("off", "Désactivée"),
        ],
        string="État",
        compute="_compute_state",
        search="_search_state",
    )

    source = fields.Selection(
        selection=[
            ("manual", "Saisie à la main"),
            ("calendar", "Détectée à l'agenda"),
        ],
        string="Origine",
        default="manual",
        required=True,
        readonly=True,
    )
    calendar_event_id = fields.Many2one(
        comodel_name="calendar.event",
        string="Événement d'agenda",
        ondelete="set null",
        readonly=True,
        help="L'événement qui a créé cette absence. La déplacer à l'agenda "
             "déplace la période ; la supprimer désactive l'absence.",
    )

    reply_ids = fields.One2many(
        comodel_name="bf.email.absence.reply",
        inverse_name="absence_id",
        string="Messages",
        copy=True,
    )
    delegate_user_id = fields.Many2one(
        comodel_name="res.users",
        string="Relève",
        help="La personne à qui s'adresser pendant l'absence. Son nom et son "
             "adresse sont disponibles dans le message par les marqueurs "
             "{releve} et {releve_courriel}.",
    )
    route_to_delegate = fields.Boolean(
        string="Confier les courriels à la relève",
        help="La fiche passe dans la boîte de la relève, en plus du message "
             "envoyé à l'expéditeur. Sans cette case, la relève est nommée "
             "mais ne reçoit rien.",
    )
    include_booking_links = fields.Boolean(
        string="Joindre mes liens rapides",
        default=True,
        help="Ajoute vos liens de signature (prise de rendez-vous, dépôt de "
             "fichier) sous le message. Utile : « je reviens le 3, prenez "
             "rendez-vous ici » évite un aller-retour.",
    )
    cooldown_days = fields.Integer(
        string="Une réponse par expéditeur tous les",
        default=DEFAULT_COOLDOWN_DAYS,
        help="En jours. La RFC 3834 recommande 7. Gmail utilise 4, Zimbra 7. "
             "Zéro répondrait à chaque message, ce que la norme interdit.",
    )
    decline_meetings = fields.Boolean(
        string="Refuser les invitations reçues pendant l'absence",
        help="Marque votre participation comme refusée pour les invitations "
             "dont la date tombe dans la période. L'événement n'est jamais "
             "modifié ni supprimé — seule votre réponse l'est.",
    )

    log_ids = fields.One2many(
        comodel_name="bf.email.auto.log",
        inverse_name="absence_id",
        string="Journal",
        readonly=True,
    )
    log_count = fields.Integer(
        string="Réponses envoyées", compute="_compute_log_count")

    # ------------------------------------------------------------------
    # Computes
    # ------------------------------------------------------------------
    @api.depends("is_template", "active", "date_from", "date_to")
    def _compute_state(self):
        now = fields.Datetime.now()
        for absence in self:
            if absence.is_template:
                absence.state = "template"
            elif not absence.active:
                absence.state = "off"
            elif absence.date_from and absence.date_from > now:
                absence.state = "planned"
            elif absence.date_to and absence.date_to < now:
                absence.state = "over"
            else:
                absence.state = "running"

    def _search_state(self, operator, value):
        """`state` is computed, so a plain search on it would be ignored.

        A stored compute would be wrong here: « en cours » changes with the
        clock, not with a write, so a stored value goes stale at midnight
        without anything touching the row.
        """
        if operator not in ("=", "!=", "in", "not in"):
            raise ValidationError(_("Filtre non pris en charge sur l'état."))
        wanted = value if isinstance(value, (list, tuple)) else [value]
        matching = self.with_context(active_test=False).search([]).filtered(
            lambda a: a.state in wanted)
        negative = operator in ("!=", "not in")
        return [("id", "not in" if negative else "in", matching.ids)]

    def _compute_log_count(self):
        counts = {}
        if self.ids:
            grouped = self.env["bf.email.auto.log"].sudo()._read_group(
                [("absence_id", "in", self.ids), ("state", "=", "sent")],
                ["absence_id"], ["__count"],
            )
            counts = {absence.id: n for absence, n in grouped}
        for absence in self:
            absence.log_count = counts.get(absence.id, 0)

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------
    @api.constrains("is_template", "date_from", "date_to")
    def _check_period(self):
        for absence in self:
            if absence.is_template:
                if absence.date_from or absence.date_to:
                    raise ValidationError(_(
                        "Un message type n'a pas de dates : il sert de patron "
                        "à des absences qui, elles, en ont."))
                continue
            if not absence.date_from or not absence.date_to:
                raise ValidationError(_(
                    "Une absence a besoin d'une date de début et d'une date "
                    "de fin. Sans date de fin, personne ne l'éteint."))
            if absence.date_to <= absence.date_from:
                raise ValidationError(_(
                    "La fin de l'absence précède son début."))

    @api.constrains("cooldown_days")
    def _check_cooldown(self):
        for absence in self:
            if not absence.is_template and absence.cooldown_days < 1:
                raise ValidationError(_(
                    "Répondre plus d'une fois par jour au même expéditeur "
                    "contredit la RFC 3834, qui recommande sept jours. "
                    "Minimum accepté : 1."))

    @api.constrains("user_id", "date_from", "date_to", "is_template", "active")
    def _check_no_overlap(self):
        """Two live absences over the same instant would race for the reply."""
        for absence in self:
            if absence.is_template or not absence.active:
                continue
            clash = self.search([
                ("id", "!=", absence.id),
                ("user_id", "=", absence.user_id.id),
                ("is_template", "=", False),
                ("date_from", "<", absence.date_to),
                ("date_to", ">", absence.date_from),
            ], limit=1)
            if clash:
                raise ValidationError(_(
                    "Cette période chevauche « %(other)s » (%(start)s → "
                    "%(end)s). Deux absences actives au même instant se "
                    "disputeraient la réponse.",
                    other=clash.name, start=clash.date_from,
                    end=clash.date_to,
                ))

    # ------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------
    def action_end_now(self):
        """Stop an absence early without deleting its history."""
        now = fields.Datetime.now()
        for absence in self:
            if absence.is_template:
                continue
            absence.date_to = now if absence.date_from < now else absence.date_from
        return True

    def action_view_logs(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Réponses d'absence — %s", self.name),
            "res_model": "bf.email.auto.log",
            "view_mode": "list,form",
            "domain": [("absence_id", "=", self.id)],
            "context": {"create": False},
        }

    def action_open_preview(self):
        self.ensure_one()
        return {
            "type": "ir.actions.act_window",
            "name": _("Aperçu de la réponse"),
            "res_model": "bf.email.absence.preview",
            "view_mode": "form",
            "target": "new",
            "context": {"default_absence_id": self.id},
        }

    # ------------------------------------------------------------------
    # Selecting the live absence
    # ------------------------------------------------------------------
    @api.model
    def _active_for(self, user, when=None):
        """The absence in force for ``user`` at ``when``, or an empty set."""
        when = when or fields.Datetime.now()
        return self.sudo().search([
            ("user_id", "=", user.id),
            ("is_template", "=", False),
            ("date_from", "<=", fields.Datetime.to_string(when)),
            ("date_to", ">=", fields.Datetime.to_string(when)),
        ], limit=1)

    # ------------------------------------------------------------------
    # The guards
    # ------------------------------------------------------------------
    def _blocked_reason(self, record):
        """Why this message must not be answered — or False to proceed.

        Every guard is answered **here**, before a mail.mail exists. An
        automatic reply already handed to the queue cannot be recalled by a
        rollback, and the one it loops with is somebody else's server.
        """
        self.ensure_one()
        Log = self.env["bf.email.auto.log"]
        headers = record.raw_headers or ""

        # Le mode test est refusé dans `_send`, pas ici : cette méthode répond
        # « pourquoi ce message est-il sans réponse », et tourner sous une
        # suite de tests n'est pas une propriété du message. Placée en tête,
        # la garde masquait toutes les autres et chaque test de garde lisait
        # « mode test » au lieu du motif qu'il vérifiait.
        if record.direction != "in":
            return "courriel sortant"
        if not record.email_from:
            return "aucun expéditeur"

        auto = re.search(r"^Auto-Submitted:\s*([^\r\n;]+)", headers,
                         re.IGNORECASE | re.MULTILINE)
        if auto and auto.group(1).strip().lower() != "no":
            return "message automatique (Auto-Submitted: %s)" % (
                auto.group(1).strip())

        if re.search(r"^List-(Id|Unsubscribe|Post|Help|Archive|Owner):",
                     headers, re.IGNORECASE | re.MULTILINE):
            return "message de liste (en-tête List-*)"

        precedence = re.search(r"^Precedence:\s*([^\r\n]+)", headers,
                               re.IGNORECASE | re.MULTILINE)
        if precedence and precedence.group(1).strip().lower() in (
                "list", "junk", "bulk"):
            return "Precedence: %s" % precedence.group(1).strip()

        return_path = re.search(r"^Return-Path:\s*<\s*>", headers,
                                re.IGNORECASE | re.MULTILINE)
        if return_path:
            return "retour nul (rebond ou notification de service)"

        sender = Log._normalize(record.email_from)
        local = sender.split("@", 1)[0] if "@" in sender else sender
        if _ROBOT_LOCALPART.match(local):
            return "adresse de service (%s)" % local

        if record.is_bulk:
            return "envoi de masse"

        # RFC 3834 §3.2: a valid address for the recipient must appear
        # explicitly in a recipient field. Bcc and list traffic are exactly
        # what this excludes, and they are the traffic that loops.
        if not (record.is_to_me or record.is_cc_to_me):
            return "je ne suis ni dans « À » ni dans « Cc »"

        own = self.env["bf.email"]._get_self_addresses(user=self.user_id)
        if sender in own:
            return "expéditeur = moi-même"

        cutoff = fields.Datetime.subtract(
            fields.Datetime.now(), days=max(1, self.cooldown_days))
        if Log._replied_since(self.user_id, record.email_from, cutoff):
            return "déjà répondu à cette adresse depuis %s jours" % (
                self.cooldown_days)

        cap = self._daily_cap()
        if cap and self._sent_today() >= cap:
            return "plafond quotidien atteint (%s)" % cap
        return False

    def _daily_cap(self):
        raw = self.env["ir.config_parameter"].sudo().get_param(
            "bf_email.absence_daily_cap")
        try:
            return max(0, int(raw)) if raw else DEFAULT_DAILY_CAP
        except ValueError:
            return DEFAULT_DAILY_CAP

    def _sent_today(self):
        self.ensure_one()
        start = fields.Datetime.now().replace(
            hour=0, minute=0, second=0, microsecond=0)
        return self.env["bf.email.auto.log"].sudo().search_count([
            ("absence_id", "=", self.id),
            ("kind", "=", "absence"),
            ("state", "=", "sent"),
            ("create_date", ">=", fields.Datetime.to_string(start)),
        ])

    # ------------------------------------------------------------------
    # Composing and sending
    # ------------------------------------------------------------------
    def _pick_reply(self, record, ctx=None):
        """The first message whose audience matches, else the default one."""
        self.ensure_one()
        default = self.env["bf.email.absence.reply"]
        for reply in self.reply_ids.sorted(lambda r: (r.sequence, r.id)):
            if not reply.condition_ids:
                default = default or reply
                continue
            if all(c._match(record, ctx) for c in reply.condition_ids):
                return reply
        return default

    def _target_lang(self, record):
        """Answer in the correspondent's language when Odoo knows it."""
        self.ensure_one()
        partner = record.partner_id or record.author_id
        return (partner.lang if partner and partner.lang
                else self.user_id.lang) or "en_US"

    def _placeholders(self, record):
        self.ensure_one()
        delegate = self.delegate_user_id
        back = fields.Datetime.context_timestamp(
            self, self.date_to) if self.date_to else None
        return {
            "{nom}": self.user_id.name or "",
            "{retour}": back.strftime("%d/%m/%Y") if back else "",
            "{releve}": delegate.name if delegate else "",
            "{releve_courriel}": (delegate.email or "") if delegate else "",
            "{motif}": self.name or "",
        }

    def _render_body(self, record, reply):
        """The message body, placeholders expanded, links appended."""
        self.ensure_one()
        lang = self._target_lang(record)
        body = reply.with_context(lang=lang).body_html or ""
        for token, value in self._placeholders(record).items():
            body = body.replace(token, html_escape(value))

        if self.include_booking_links:
            links = self._booking_links_html()
            if links:
                body += links
        return body

    def _booking_links_html(self):
        """The owner's signature quick links, when that module is installed.

        Read through the field registry rather than a manifest dependency:
        the signature module is optional, and a routing module has no business
        requiring a branding one.
        """
        self.ensure_one()
        user = self.user_id
        if "bf_signature_link_ids" not in user._fields:
            return ""
        try:
            links = user.sudo().bf_signature_link_ids
            if getattr(user, "bf_signature_use_company_links", False):
                links |= user.company_id.sudo().bf_signature_link_ids
        except Exception:
            return ""
        links = links.sorted(lambda link: (link.sequence, link.id))
        if not links:
            return ""
        items = "".join(
            '<li style="margin:2px 0;"><a href="%s" style="color:#3C6E9F;">'
            "%s%s</a></li>" % (
                html_escape(link.url),
                (html_escape(link.icon) + "&#160;") if link.icon else "",
                html_escape(link.name),
            )
            for link in links
        )
        return ('<ul style="margin:12px 0 0 0;padding-left:18px;'
                'font-size:13px;">%s</ul>' % items)

    def _send(self, record, ctx=None):
        """Answer ``record``. Returns the mail.mail, or an empty set."""
        self.ensure_one()
        Log = self.env["bf.email.auto.log"]

        if Log._test_mode():
            Log._log(record, record.email_from or "?", "skipped",
                     kind="absence", reason="mode test : aucun envoi",
                     absence=self)
            return self.env["mail.mail"]

        blocked = self._blocked_reason(record)
        if blocked:
            Log._log(record, record.email_from or "?", "skipped",
                     kind="absence", reason=blocked, absence=self)
            return self.env["mail.mail"]

        reply = self._pick_reply(record, ctx)
        if not reply:
            Log._log(record, record.email_from, "skipped", kind="absence",
                     reason="aucun message ne vise cet expéditeur",
                     absence=self)
            return self.env["mail.mail"]

        owner = self.user_id
        from_addr = (record.account_id.login or owner.email
                     or owner.partner_id.email)
        if not from_addr:
            Log._log(record, record.email_from, "error", kind="absence",
                     reason="aucune adresse d'expédition pour %s" % owner.name,
                     absence=self)
            return self.env["mail.mail"]

        subject = record.subject or _("(sans objet)")
        if not subject.lower().startswith("auto:"):
            subject = "Auto: %s" % subject

        headers = {
            # RFC 3834 §5: this is what stops the responder on the other side.
            "Auto-Submitted": "auto-replied",
            # Microsoft's equivalent, honoured by Exchange and Outlook.
            "X-Auto-Response-Suppress": "All",
            "X-BF-Absence": str(self.id),
        }
        if record.message_id_header:
            headers["In-Reply-To"] = record.message_id_header
            headers["References"] = record.message_id_header

        try:
            mail = self.env["mail.mail"].sudo().create({
                "subject": subject[:250],
                "body_html": self._render_body(record, reply),
                "email_from": formataddr((owner.name, from_addr)),
                "email_to": record.email_from,
                "headers": repr(headers),
                "auto_delete": True,
                # RFC 3834 §3.1.6: no attachments, and nothing of the
                # original message's non-text content comes back out.
                "attachment_ids": [(5, 0, 0)],
            })
        except Exception as exc:
            _logger.warning(
                "bf.email.absence %s: réponse impossible pour bf.email %s",
                self.id, record.id, exc_info=True,
            )
            Log._log(record, record.email_from, "error", kind="absence",
                     reason=str(exc), absence=self)
            return self.env["mail.mail"]

        Log._log(record, record.email_from, "sent", kind="absence",
                 mail=mail, absence=self)
        _logger.info(
            "bf.email.absence %s: réponse d'absence à %s (bf.email %s)",
            self.id, record.email_from, record.id,
        )

        if self.route_to_delegate and self.delegate_user_id:
            try:
                record.sudo().write(
                    {"user_id": self.delegate_user_id.id})
            except Exception:
                _logger.warning(
                    "bf.email.absence %s: fiche %s non confiée à la relève",
                    self.id, record.id, exc_info=True,
                )
        return mail

    # ------------------------------------------------------------------
    # Calendar-driven absences
    # ------------------------------------------------------------------
    @api.model
    def _calendar_pattern(self):
        raw = self.env["ir.config_parameter"].sudo().get_param(
            "bf_email.absence_calendar_pattern")
        return raw or DEFAULT_CALENDAR_PATTERN

    @api.model
    def _cron_sync_calendar(self):
        """Create, move and retire absences from the calendar.

        Only touches rows it created (`source='calendar'`). A period typed by
        hand is never moved by a cron: the person who typed it is the one who
        decides when it ends.
        """
        Users = self.env["res.users"].sudo()
        owners = Users.search([
            ("share", "=", False),
            ("bf_absence_from_calendar", "=", True),
        ])
        if not owners:
            return 0
        pattern = re.compile(self._calendar_pattern())
        horizon_from = fields.Datetime.subtract(fields.Datetime.now(), days=1)
        horizon_to = fields.Datetime.add(fields.Datetime.now(), days=180)
        touched = 0

        for user in owners:
            template = self.sudo().search([
                ("user_id", "=", user.id), ("is_template", "=", True),
            ], limit=1)
            if not template:
                _logger.info(
                    "bf.email.absence: %s a demandé la détection à l'agenda "
                    "mais n'a pas de message type — rien à copier.",
                    user.login,
                )
                continue

            events = self.env["calendar.event"].sudo().search([
                ("user_id", "=", user.id),
                ("start", "<=", fields.Datetime.to_string(horizon_to)),
                ("stop", ">=", fields.Datetime.to_string(horizon_from)),
            ])
            matching = events.filtered(lambda e: pattern.search(e.name or ""))
            touched += self._sync_user_calendar(user, template, matching)
        return touched

    def _sync_user_calendar(self, user, template, events):
        """One user's calendar-driven absences, reconciled with ``events``."""
        existing = self.sudo().with_context(active_test=False).search([
            ("user_id", "=", user.id),
            ("source", "=", "calendar"),
        ])
        by_event = {a.calendar_event_id.id: a for a in existing
                    if a.calendar_event_id}
        touched = 0

        for event in events:
            start, stop = self._event_window(event)
            absence = by_event.pop(event.id, None)
            if absence:
                vals = {}
                if absence.date_from != start:
                    vals["date_from"] = start
                if absence.date_to != stop:
                    vals["date_to"] = stop
                if not absence.active:
                    vals["active"] = True
                if vals:
                    absence.sudo().write(vals)
                    touched += 1
                    _logger.info(
                        "bf.email.absence %s: période reprise de l'agenda "
                        "(%s → %s)", absence.id, start, stop)
                continue
            created = self.sudo().create({
                "name": event.name or _("Absence"),
                "user_id": user.id,
                "company_id": user.company_id.id,
                "source": "calendar",
                "calendar_event_id": event.id,
                "date_from": start,
                "date_to": stop,
                "delegate_user_id": template.delegate_user_id.id,
                "route_to_delegate": template.route_to_delegate,
                "include_booking_links": template.include_booking_links,
                "cooldown_days": template.cooldown_days,
                "decline_meetings": template.decline_meetings,
                "reply_ids": [
                    (0, 0, reply._copy_vals()) for reply in template.reply_ids
                ],
            })
            touched += 1
            _logger.info(
                "bf.email.absence %s: créée depuis l'événement « %s » "
                "(%s → %s)", created.id, event.name, start, stop)

        # Events that no longer match — renamed, deleted, or moved out of the
        # horizon. Deactivate rather than delete: the journal points at them.
        for orphan in by_event.values():
            if orphan.active:
                orphan.sudo().write({"active": False})
                touched += 1
                _logger.info(
                    "bf.email.absence %s: désactivée, son événement d'agenda "
                    "a disparu", orphan.id)
        return touched

    @api.model
    def _event_window(self, event):
        """Start and end of an event, all-day convention included.

        Odoo stores an all-day event with both ends at 00:00:00 and a `stop`
        on the LAST day. Taken literally, a one-day absence would last zero
        second and never fire.
        """
        start, stop = event.start, event.stop
        if event.allday:
            stop = stop + timedelta(hours=23, minutes=59, seconds=59)
        return start, stop

    # ------------------------------------------------------------------
    # Declining meetings
    # ------------------------------------------------------------------
    @api.model
    def _cron_decline_meetings(self):
        """Decline the invitations that land inside a running absence.

        Narrow on purpose: it writes ONE field on the absent person's own
        attendee row, and only from « needs action ». It never touches the
        event, never removes an attendee, and never answers for anybody else —
        an automatic hand in somebody else's calendar is how a synchronisation
        turns into a data loss.
        """
        now = fields.Datetime.now()
        running = self.sudo().search([
            ("is_template", "=", False),
            ("decline_meetings", "=", True),
            ("date_from", "<=", fields.Datetime.to_string(now)),
            ("date_to", ">=", fields.Datetime.to_string(now)),
        ])
        declined = 0
        for absence in running:
            partner = absence.user_id.partner_id
            if not partner:
                continue
            attendees = self.env["calendar.attendee"].sudo().search([
                ("partner_id", "=", partner.id),
                ("state", "=", "needsAction"),
                ("event_id.start", ">=",
                 fields.Datetime.to_string(absence.date_from)),
                ("event_id.start", "<=",
                 fields.Datetime.to_string(absence.date_to)),
            ])
            # Never decline the event that created the absence.
            if absence.calendar_event_id:
                attendees = attendees.filtered(
                    lambda a: a.event_id != absence.calendar_event_id)
            if not attendees:
                continue
            attendees.write({"state": "declined"})
            declined += len(attendees)
            _logger.info(
                "bf.email.absence %s: %s invitation(s) refusée(s) pendant "
                "l'absence", absence.id, len(attendees),
            )
        return declined


class BfEmailAbsenceReply(models.Model):
    _name = "bf.email.absence.reply"
    _description = "Message d'absence par audience"
    _order = "sequence, id"

    absence_id = fields.Many2one(
        comodel_name="bf.email.absence",
        string="Absence",
        required=True,
        index=True,
        ondelete="cascade",
    )
    sequence = fields.Integer(string="Séquence", default=10)
    name = fields.Char(
        string="Audience",
        required=True,
        help="Pour vous : « Clients », « Interne », « Tout le monde ».",
    )
    condition_ids = fields.One2many(
        comodel_name="bf.email.rule.condition",
        inverse_name="absence_reply_id",
        string="S'applique quand",
        copy=True,
        help="Les mêmes conditions que les règles de routage. Sans "
             "condition, ce message est celui que reçoit tout le monde que "
             "les autres lignes n'ont pas attrapé.",
    )
    is_catch_all = fields.Boolean(
        string="Message par défaut",
        compute="_compute_is_catch_all",
        store=True,
    )
    body_html = fields.Html(
        string="Message",
        required=True,
        translate=True,
        sanitize=True,
        help="Marqueurs disponibles : {nom}, {retour}, {releve}, "
             "{releve_courriel}, {motif}.\n\n"
             "Le champ est traduisible : rédigez-le dans votre langue, puis "
             "traduisez-le, et chaque correspondant reçoit la version de la "
             "langue enregistrée sur sa fiche.",
    )

    @api.depends("condition_ids")
    def _compute_is_catch_all(self):
        for reply in self:
            reply.is_catch_all = not reply.condition_ids

    @api.constrains("absence_id", "condition_ids")
    def _check_single_catch_all(self):
        """Two default messages would make the answer depend on row order."""
        for reply in self:
            if reply.condition_ids:
                continue
            twin = self.search_count([
                ("absence_id", "=", reply.absence_id.id),
                ("id", "!=", reply.id),
                ("condition_ids", "=", False),
            ])
            if twin:
                raise ValidationError(_(
                    "Deux messages sans condition : lequel serait le message "
                    "par défaut ? Donnez une audience à l'un des deux."))

    def _copy_vals(self):
        """Values to clone this line onto another absence."""
        self.ensure_one()
        return {
            "sequence": self.sequence,
            "name": self.name,
            "body_html": self.body_html,
            "condition_ids": [
                (0, 0, {
                    "kind": c.kind,
                    "sequence": c.sequence,
                    "field_name": c.field_name,
                    "operator": c.operator,
                    "value": c.value,
                    "header_name": c.header_name,
                    "value_direction": c.value_direction,
                    "value_category": c.value_category,
                    "value_priority": c.value_priority,
                })
                for c in self.condition_ids
            ],
        }
