from . import test_operations
from . import test_preventive_plan
from . import test_shift
from . import test_indicators
from . import test_notification
from . import test_repair_scope
from . import test_workshop_menus
from . import test_reader_language
from . import test_building_visibility
