from . import onchange_guard
from . import helpdesk_macro
from . import helpdesk_auto_tag_rule
from . import helpdesk_ticket_stage
from . import helpdesk_ticket_team
from . import helpdesk_ticket
from . import helpdesk_ticket_csat
from . import helpdesk_client_digest
from . import helpdesk_notify
from . import helpdesk_article
from . import account_analytic_line
from . import meeting_record
from . import onboarding_onboarding
from . import bf_dashboard
from . import helpdesk_ticket_client360
from . import helpdesk_ticket_presence
from . import mail_thread
from . import res_company
from . import mail_mail
from . import helpdesk_triage
from . import orphan_views
from . import closing_template
from . import mail_compose_message
