{
    "name": "Symbifox — Helpdesk",
    "summary": "Fork OCA helpdesk_mgmt with BF integrations: hour bank, ticket timesheets, waiting states, branded public form, ntfy critical hook",
    "version": "18.0.4.15.4",
    "category": "After-Sales",
    "author": "Les services de consultation Blue Fox, Inc.",
    "website": "https://symbifox.com",
    'license': 'AGPL-3',
    "depends": [
        "website",
        "helpdesk_mgmt",
        "helpdesk_mgmt_project",
        "hr_timesheet",
        "bf_hour_bank",
        "bf_persona",
        "project_knowledge_matrix",
        "bf_meeting",
        "bf_ai_bridge",
        "survey",
        "bf_home",
        "bf_onboarding_base",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/helpdesk_notify_security.xml",
        "data/helpdesk_data.xml",
        "data/mail_templates.xml",
        "data/bf_onboarding.xml",
        "views/helpdesk_menu_views.xml",
        "views/helpdesk_ticket_team_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_macro_views.xml",
        "views/helpdesk_ticket_workspace_views.xml",
        "views/helpdesk_auto_tag_views.xml",
        "views/helpdesk_ticket_stage_views.xml",
        "views/public_form_templates.xml",
        "views/portal_ticket_templates.xml",
        "views/helpdesk_ticket_csat_views.xml",
        "views/csat_templates.xml",
        "views/helpdesk_article_views.xml",
        "views/help_center_templates.xml",
        "views/mail_layout.xml",
        "views/brand_variables.xml",
        "views/client_notify_templates.xml",
        "views/helpdesk_notify_views.xml",
        "views/helpdesk_triage_views.xml",
        "views/portal_brand.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_helpdesk/static/src/presence/ticket_presence.js",
            "bf_helpdesk/static/src/presence/ticket_presence.xml",
        ],
        "web.assets_frontend": [
            "bf_helpdesk/static/src/scss/public_form.scss",
            "bf_helpdesk/static/src/scss/portal_brand.scss",
            "bf_helpdesk/static/src/help/suggestions.esm.js",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "application": True,
}
