from . import test_bf_note
from . import test_bf_note_reroute
from . import test_langue
from . import test_mobile
from . import test_mobile_http
from . import test_isolation_menage
from . import test_isolation_mobile
from . import test_isolation_adverse
from . import test_couleurs
from . import test_couleurs_http
