from . import test_mobile
from . import test_registre
from . import test_comptes
from . import test_personnalite
from . import test_tours
from . import test_plafond
from . import test_nommage
from . import test_liste
from . import test_fermeture
from . import test_envoyer_vers_gen
from . import test_non_lu
from . import test_retouches
