from . import test_sdm
from . import test_appariement
from . import test_pastille
from . import test_portes
from . import test_lecture
from . import test_gestes_neufs
from . import test_liens
from . import test_socle_menu_differe
from . import test_appareil_securite
