{
    "name": "Gestion des courriels",
    "summary": "Inbox unifiée IMAP + chatters Odoo, avec re-routage UI",
    "version": "18.0.11.8.0",
    "category": "Productivity",
    'website': 'https://symbifox.com',
    "author": "Les services de consultation Blue Fox, Inc.",
    'license': 'Other proprietary',
    "application": True,
    "post_init_hook": "post_init_hook",
    "installable": True,
    "depends": [
        "base",
        "mail",
        "mail_composer_cc_bcc",
        "mail_quoted_reply",
        "calendar",
        "project",
        "account",
        "bf_onboarding_base",
        "bf_chatter_target",
    ],
    "data": [
        "security/email_security.xml",
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "data/email_sync_cron.xml",
        "data/email_sync_imap_cron.xml",
        "data/imap_mirror_cron.xml",
        "data/imap_reconcile_cron.xml",
        "data/imap_writeback_sweep_cron.xml",
        "data/expected_reply_minutes_cron.xml",
        "data/auto_link_orphans_cron.xml",
        "data/forward_log_prune_cron.xml",
        "data/absence_cron.xml",
        "data/bf_email_rule_default.xml",
        "data/calendar_reminder_cron.xml",
        "data/bf_onboarding.xml",
        "wizard/bf_email_initial_sync_views.xml",
        "wizard/bf_email_reroute_views.xml",
        "wizard/bf_email_imap_backfill_views.xml",
        "wizard/bf_email_snooze_views.xml",
        "wizard/bf_email_browser_views.xml",
        "wizard/bf_email_guess_route_views.xml",
        "wizard/bf_email_rule_quick_views.xml",
        "views/bf_email_account_views.xml",
        "views/bf_email_identity_views.xml",
        "views/bf_email_views.xml",
        "views/bf_email_rule_views.xml",
        "views/bf_email_absence_views.xml",
        "views/bf_email_dashboard_views.xml",
        "views/mail_compose_message_views.xml",
        "views/mail_scheduled_message_views.xml",
        "views/res_config_settings_views.xml",
        "views/bf_email_menu.xml",
        "views/res_partner_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # Socle commun aux deux actions clientes courriel — doit être
            # chargé avant elles.
            "bf_email_management/static/src/scss/bf_email_ui.scss",
            "bf_email_management/static/src/js/bf_email_ui_common.js",
            "bf_email_management/static/src/js/bf_email_dashboard.js",
            "bf_email_management/static/src/js/bf_email_chatter_action.js",
            "bf_email_management/static/src/js/bf_email_preview_list.js",
            "bf_email_management/static/src/xml/bf_email_preview_list.xml",
            "bf_email_management/static/src/js/bf_calendar_reminder.js",
            "bf_email_management/static/src/scss/bf_calendar_reminder.scss",
            # Arrival notice. After the calendar reminder and unrelated to
            # it: this service replaces nothing, it sits alongside.
            "bf_email_management/static/src/js/bf_email_popup.js",
            "bf_email_management/static/src/scss/bf_email_popup.scss",
            "bf_email_management/static/src/js/bf_email_browser.js",
            "bf_email_management/static/src/js/bf_email_inbox.js",
            "bf_email_management/static/src/js/bf_email_new_record_dropdown.js",
            "bf_email_management/static/src/xml/bf_email_dashboard.xml",
            "bf_email_management/static/src/xml/bf_email_browser.xml",
            "bf_email_management/static/src/xml/bf_email_inbox.xml",
            "bf_email_management/static/src/xml/bf_email_chatter_badge.xml",
            "bf_email_management/static/src/xml/bf_email_new_record_dropdown.xml",
        ],
    },
}
