{
    "name": "Healthy Fox",
    "summary": "Suivi santé, entraînement et nutrition : médicaments, signes vitaux, analyses, examens, séances (import GPX), journal alimentaire (code-barres Open Food Facts), métriques quotidiennes et journal d'humeur privé",
    "version": "18.0.2.5.1",
    "category": "Santé",
    "website": "https://symbifox.com",
    "author": "Les services de consultation Blue Fox, Inc.",
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "depends": [
        "base",
        "mail",
        "web",
    ],
    "external_dependencies": {
        "python": ["requests"],
    },
    "data": [
        "security/health_security.xml",
        "security/ir.model.access.csv",
        "data/mail_activity_type.xml",
        "data/health_cron.xml",
        "data/health_screening_data.xml",
        "data/health_mood_data.xml",
        "views/health_medication_views.xml",
        "views/health_medication_log_views.xml",
        "views/health_vital_views.xml",
        "views/health_lab_test_views.xml",
        "views/health_symptom_log_views.xml",
        "views/health_condition_views.xml",
        "views/health_substance_log_views.xml",
        "views/health_reduction_step_views.xml",
        "views/health_screening_views.xml",
        "views/health_workout_views.xml",
        "views/health_food_views.xml",
        "views/health_meal_log_views.xml",
        "views/health_nutrition_goal_views.xml",
        "views/health_dashboard_views.xml",
        "views/health_daily_log_wizard_views.xml",
        "views/health_mood_views.xml",
        "report/health_mood_report.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_health/static/src/js/health_dashboard.js",
            "bf_health/static/src/xml/health_dashboard.xml",
            "bf_health/static/src/xml/chatter_note_only.xml",
        ],
    },
    "icon": "/bf_health/static/description/icon.png",
}
