from . import privacy_breach_notice
from . import ir_attachment
from . import base_partner_merge
from . import mail_template
from . import mail_message
from . import mail_compose_message
from . import mail_activity
from . import mail_attached
from . import mail_followers
