from . import account_move
from . import mail_followers
from . import membership_type
from . import membership
from . import partner_merge
from . import receipt
from . import receipt_report
from . import res_company
from . import res_config_settings
from . import res_partner
